# Generated by Django 3.2.15 on 2022-08-20 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medamapp', '0002_auto_20220813_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.AddField(
            model_name='location',
            name='location_external_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='sensor',
            name='device_external_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'Out-of-order'), ('d', 'Deployed'), ('n', 'New'), ('r', 'Ready')], default='n', help_text='Senor status', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='user_external_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
